kind: Service
apiVersion: v1
metadata:
  name: mavenproject1
  labels:
    app: mavenproject1
spec:
  type: NodePort
  selector:
    app: mavenproject1
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mavenproject1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mavenproject1
  template:
    metadata:
      labels:
        app: mavenproject1
        version: v1
    spec:
      containers:
      - name: mavenproject1
        image: mavenproject1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
